### PR TITLE
Add optional prop `clearOnClose` that defaults to true.

### PR DESCRIPTION
**Pull request by bolivier**

### CODE REVIEW

**Comment by bolivier** [comment]
@paranoidjk

**Comment by paranoidjk** [comment]
I think this is a bug, what you did is right, we should clean the component `state.value` when user click clear icon, not just clear the showing text. cc @benjycui

**Comment by paranoidjk** [comment]
@afc163 may be more familiar with this component, I suggest we do not add api, but do `clearOnClose` by default.

**Comment by bolivier** [comment]
Clearing the state is a good default, but I need to use the "X" as a simple close.  Modifying the api to offer that as an option and defaulting to `clearOnClose` seems reasonable.

**Comment by benjycui** [comment]
Nope, the  `x` button means clear, not close.

**Comment by paranoidjk** [comment]
@benjycui 

untitled

**Comment by bolivier** [comment]
If you aren't open to to changing the button api specifically, would it be acceptable to add a customizable callback to the close button?

**Comment by paranoidjk** [comment]
@bolivier Thx for your pr. But i am going to close this because of below reasons:
- Your use case is very rare, normally we do not want clear the selected value when close this popup picker panel;
- If you do want to do this,  just clear value in  `props.onClose` callback

untitled

**Pull request closed without merging**
